name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, next]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test --ci --coverage --runInBand

      - name: Codecov
        continue-on-error: true
        run: npm run codecov

      - name: Check bundle size
        continue-on-error: true
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
        run: npm run bundlewatch
