name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, next]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: .yarn
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --runInBand && yarn codecov
